title: Ivan Netkachev
logo: /assets/img/logo.png
description: the politics of poems and algorithms
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

collections:
  projects:
    output: true